services:
  postgres:
    image: postgres:18
    container_name: isotope-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - isotope-postgres-data:/var/lib/postgresql

  nuclei-test-target:
    build:
      context: ./test-target
    container_name: isotope-nuclei-target
    restart: unless-stopped
    ports:
      - "8085:80"

volumes:
  isotope-postgres-data:
